# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Create and activate virtual environment
      run: |
        uv venv .venv
        echo ".venv/bin" >> $GITHUB_PATH
    - name: Install dependencies with uv
      run: |
        uv pip install --upgrade flake8 pytest
        if [ -f requirements.txt ]; then uv pip install -r requirements.txt; fi
    - name: Set Recursion Limit
      run: |
        python -c "import sys; sys.setrecursionlimit(1500)"
    - name: Lint with flake8
      run: |
        # Ignore RecursionError and specific files like sympy
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --extend-ignore=E501,F401,W503 --exclude=.venv,sympy
    - name: Test with pytest
      run: |
        pytest
